default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/schmir/pre-commit-go-hooks
    rev: "714ba3b45c87543bb6bc74a511b2da5238e93f38"
    hooks:
      - id: gci
        args:
          [
            "--custom-order",
            "-sStandard",
            "-sDefault",
            "-sPrefix(github.com/schmir/temple-go)",
          ]
      - id: golines-gofumpt
